### DISCUSSION TITLE
Docker DisboxApp

### DISCUSSION THREAD

**Discussion by zzadri** [DisboxApp/web#107] [Ideas]
Hi, thanks for this useful tool!

I think it's a shame you didn't think of making a docker ...

but here it is! 

**docker-compose.yml**
```
version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Replace with the five-digit port of your choice
    volumes:
      - ./web:/app
```

**Dockerfile**
```
FROM node:14
WORKDIR /app

COPY web/package.json web/package-lock.json ./
RUN npm install

COPY web/ .

EXPOSE 3000
CMD ["npm", "start"]
```

**the root**
![image](https://github.com/DisboxApp/web/assets/44464332/19b5739d-b528-49c2-a2d1-46015396cc1c)

**command for run**
`docker-compose build && docker-compose run web npm install && docker-compose up`
